# Generated by Django 5.0.3 on 2024-10-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cliente_cliente_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='clientemapaclienteobjetivo',
            options={'verbose_name': 'clienteMapaClienteObjetivo', 'verbose_name_plural': 'clienteMapaClienteObjetivo'},
        ),
        migrations.AlterModelOptions(
            name='clienteusuario',
            options={'verbose_name': 'clienteUsuario', 'verbose_name_plural': 'clienteUsuario'},
        ),
        migrations.AlterModelOptions(
            name='datosbucketsoutliers',
            options={'verbose_name': 'datosBucketOutliers', 'verbose_name_plural': 'datosBucketOutliers'},
        ),
        migrations.AlterModelOptions(
            name='ejecutivo',
            options={'verbose_name': 'ejecutivo', 'verbose_name_plural': 'ejecutivos'},
        ),
        migrations.AlterModelOptions(
            name='objetivo',
            options={'verbose_name': 'objetivo', 'verbose_name_plural': 'objetivos'},
        ),
        migrations.AlterModelOptions(
            name='objetivoconfig',
            options={'verbose_name': 'objetivoConfig', 'verbose_name_plural': 'objetivoConfig'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'pais', 'verbose_name_plural': 'paises'},
        ),
        migrations.AlterModelOptions(
            name='parametrosiniciales',
            options={'verbose_name': 'parametrosIniciales', 'verbose_name_plural': 'parametrosIniciales'},
        ),
        migrations.AlterModelOptions(
            name='procesado',
            options={'verbose_name': 'procesado', 'verbose_name_plural': 'procesado'},
        ),
        migrations.RemoveConstraint(
            model_name='datosbucketsoutliers',
            name='datos_buckets_outliers_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='parametrosiniciales',
            name='parametros_iniciales_constraint',
        ),
    ]
