# Generated by Django 5.0.3 on 2024-10-14 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('descripcion', models.CharField(max_length=256)),
                ('max_usuarios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosBucketsOutliers',
            fields=[
                ('bucket_outlier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('fecha_calculo', models.DateField()),
                ('dato_id', models.IntegerField()),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ejecutivo',
            fields=[
                ('ejecutivo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('telefono', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('objetivo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
                ('descripcion', models.CharField(max_length=256)),
                ('servicio_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoConfig',
            fields=[
                ('objetivo_config_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
                ('periodo_entrenamiento', models.IntegerField()),
                ('sensibilidad_z', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ParametrosIniciales',
            fields=[
                ('bucket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('objetivo_id', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('maximo', models.IntegerField()),
                ('cantidad_datos', models.IntegerField()),
                ('promedio', models.FloatField()),
                ('desviacion_estandar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Procesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('objetivo_id', models.SmallIntegerField()),
                ('bucket_id', models.SmallIntegerField()),
                ('minimo', models.IntegerField()),
                ('maximo', models.IntegerField()),
                ('cantidad_datos', models.IntegerField()),
                ('promedio', models.FloatField()),
                ('desviacion_estandar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClienteMapaClienteObjetivo',
            fields=[
                ('cliente_mapa_cliente_objetivo', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteUsuario',
            fields=[
                ('cliente_usuario_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('clave', models.CharField(max_length=256)),
                ('fecha_creacion', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('cargo', models.CharField(max_length=256)),
                ('telefono', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='datosbucketsoutliers',
            constraint=models.UniqueConstraint(fields=('dato_id',), name='datos_buckets_outliers_constraint'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ejecutivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ejecutivo'),
        ),
        migrations.AddField(
            model_name='clientemapaclienteobjetivo',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.objetivo'),
        ),
        migrations.AddField(
            model_name='objetivoconfig',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.objetivo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pais'),
        ),
        migrations.AddConstraint(
            model_name='parametrosiniciales',
            constraint=models.UniqueConstraint(fields=('fecha', 'objetivo_id'), name='parametros_iniciales_constraint'),
        ),
    ]
