# Generated by Django 5.0.3 on 2024-10-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_clienteusuario_groups_clienteusuario_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteusuario',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
