# Generated by Django 5.0.3 on 2024-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clienteusuario_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteusuario',
            name='fecha_expiracion',
            field=models.DateField(null=True),
        ),
    ]
